.TH PDEATH 1 PDEATH
.SH NAME
pdeath \- Run a command that is killed when its parent exits
.SH SYNOPSIS
.B pdeath
(-L |
.RB \fIsignal\fP[( + | - )\fIoff\fP]
.I command
.RI [ argument ]\ ...)
.SH DESCRIPTION
.B pdeath
runs the select command with the parent death signal set to
.I signal
plus or minus
.IR off .
This means that the process receives this signal when its
parent process dies.
.SH OPTIONS
.TP
.B \-L
List all signals.
.SH LIMITATIONS
.B pdeath
cannot be used on binaries with set-user-ID or set-group-ID set.
.SH AUTHORS
Mattias Andrée
.RI < m@maandree.se >
